CREATE TABLE Person (
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	fio varchar NOT NULL UNIQUE,
	date_of_birth DATE
);

CREATE TABLE Book(
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	person_id int REFERENCES Person(id) ON DELETE SET NULL,
	book_name varchar NOT NULL,
	author varchar,
	year_of_relese int NOT NULL check (year_of_relese > 1700)
);