CREATE TABLE Person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio varchar(100) NOT NULL UNIQUE,
    yearOfBirth int NOT NULL
);

CREATE TABLE Book (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    author varchar(100) NOT NULL,
    yearOfRelese int NOT NULL,
    person_id int REFERENCES Person(id) ON DELETE SET NULL
);